### Import Package

In [1]:
import numpy as np

### Computing the inverse of a matrix with NumPy

In [2]:
A = np.array([[4,5,7],[5,10,6],[3,9,2]])
A

array([[ 4,  5,  7],
       [ 5, 10,  6],
       [ 3,  9,  2]])

In [3]:
np.linalg.inv(A)

array([[-3.77777778,  5.88888889, -4.44444444],
       [ 0.88888889, -1.44444444,  1.22222222],
       [ 1.66666667, -2.33333333,  1.66666667]])

In [4]:
np.matmul(A, np.linalg.inv(A))

array([[ 1.00000000e+00,  4.44089210e-16,  1.55431223e-15],
       [ 8.88178420e-16,  1.00000000e+00,  1.33226763e-15],
       [ 4.44089210e-15, -2.66453526e-15,  1.00000000e+00]])

### Computing the Adjugate Matrix and checking its correctness

In [5]:
np.linalg.det(A)

8.999999999999973

In [6]:
round(np.linalg.det(A))

9

In [7]:
A_adj = np.linalg.inv(A) * round(np.linalg.det(A))
A_adj

array([[-34.,  53., -40.],
       [  8., -13.,  11.],
       [ 15., -21.,  15.]])

In [8]:
(1/np.linalg.det(A)) * A_adj

array([[-3.77777778,  5.88888889, -4.44444444],
       [ 0.88888889, -1.44444444,  1.22222222],
       [ 1.66666667, -2.33333333,  1.66666667]])

### Computing the inverse of the matrix over a specifed ring: $\mathbb{Z}_{26}$

In [9]:
A_inv_det_Z26 = pow(round(np.linalg.det(A)), -1, 26)
A_inv_det_Z26

3

In [10]:
A_inv_Z26 = A_inv_det_Z26 * A_adj
A_inv_Z26

array([[-102.,  159., -120.],
       [  24.,  -39.,   33.],
       [  45.,  -63.,   45.]])

In [11]:
A_inv_Z26 = A_inv_Z26 % 26
A_inv_Z26

array([[ 2.,  3., 10.],
       [24., 13.,  7.],
       [19., 15., 19.]])

In [12]:
np.matmul(A, A_inv_Z26)

array([[261., 182., 208.],
       [364., 235., 234.],
       [260., 156., 131.]])

In [13]:
np.matmul(A, A_inv_Z26) % 26

array([[1.00000000e+00, 5.68434189e-14, 2.84217094e-14],
       [5.68434189e-14, 1.00000000e+00, 2.84217094e-14],
       [1.13686838e-13, 0.00000000e+00, 1.00000000e+00]])

In [14]:
np.round_(np.matmul(A, A_inv_Z26) % 26)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
A_inv_Z26[0,0]

1.9999999999997158

In [16]:
type(A_inv_Z26[0,0])

numpy.float64

### NumPy returns a float matrix! 

### How to get an integer matrix:

In [17]:
np.round_(A_inv_Z26)

array([[ 2.,  3., 10.],
       [24., 13.,  7.],
       [19., 15., 19.]])

In [18]:
np.round_(A_inv_Z26)[0,0]

2.0

In [19]:
type(np.round_(A_inv_Z26)[0,0])

numpy.float64

`np.round_` (round to the given number of decimals; defualt: `decimals=0`, same as `np.rint`) does not help either.

We can simply change the type to integer. Let's see if it works:

In [20]:
A_inv_int_Z26 = A_inv_Z26.astype(int)
A_inv_int_Z26

array([[ 1,  3,  9],
       [24, 12,  7],
       [19, 14, 19]])

In [21]:
A_inv_int_Z26[0,0]

1

In [22]:
type(A_inv_int_Z26[0,0])

numpy.int32

Finally, this works as expected!

But in general, use caution when using this approach for finding the inverse of a matrix over a finite ring, especially for large numbers. 

### I hope you learnt something new! Thanks! :) 