### Link to YouTube Video

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/mlUoYUzakPw/0.jpg)](https://youtu.be/mlUoYUzakPw)

https://youtu.be/mlUoYUzakPw

#### Import packages

In [1]:
import numpy as np

#### Define plaintext, key and set up useful variables

In [2]:
PT = "Hill Cipher"
PT

'Hill Cipher'

In [3]:
PT = PT.replace(" ", "")
PT

'HillCipher'

In [4]:
PT = PT.lower()
PT

'hillcipher'

In [5]:
key = "test"
key

'test'

In [6]:
(chr(97), ord('a'))

('a', 97)

In [7]:
EAM = {chr(i):i-97 for i in range(97, 97+26)}
print(EAM)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [8]:
EAM_rev = {i-97:chr(i) for i in range(97, 97+26)}
print(EAM_rev)

{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j', 10: 'k', 11: 'l', 12: 'm', 13: 'n', 14: 'o', 15: 'p', 16: 'q', 17: 'r', 18: 's', 19: 't', 20: 'u', 21: 'v', 22: 'w', 23: 'x', 24: 'y', 25: 'z'}


In [9]:
PT_numbers = [EAM[i] for i in PT]
PT_numbers

[7, 8, 11, 11, 2, 8, 15, 7, 4, 17]

In [10]:
key_numbers = [EAM[i] for i in key]
key_numbers

[19, 4, 18, 19]

In [11]:
BL = len(key_numbers)//2 # Block Length
BL

2

Alternatively, `len(key_numbers)` must be a perfect square, if it is a key in Hill Cipher, thus we can use the built in `pow` function in Python to find its square root:

In [12]:
int(pow(len(key_numbers), 1/2))

2

Use caution when using `int(pow(n ** 2, 1/2))` for large values of n.

In [13]:
key_matrix = np.array(key_numbers).reshape(BL, BL)
print(key_matrix)

[[19  4]
 [18 19]]


In [14]:
PT_array = np.array(PT_numbers)
print(PT_array)

[ 7  8 11 11  2  8 15  7  4 17]


### Encryption

In [15]:
len(PT_array)/BL

5.0

In [16]:
PT_blocks = np.split(PT_array, len(PT_array)/BL)
print(PT_blocks)

[array([7, 8]), array([11, 11]), array([2, 8]), array([15,  7]), array([ 4, 17])]


In [17]:
PT_blocks[0]

array([7, 8])

In [18]:
np.matmul(PT_blocks[0], key_matrix) % 26

array([17, 24], dtype=int32)

In [19]:
CT_blocks = [np.matmul(PT_blocks[i], key_matrix) % 26 for i in range(len(PT)//BL)]
CT_blocks

[array([17, 24], dtype=int32),
 array([17, 19], dtype=int32),
 array([0, 4], dtype=int32),
 array([21, 11], dtype=int32),
 array([18,  1], dtype=int32)]

In [20]:
CT_array = np.concatenate(CT_blocks)
CT_array

array([17, 24, 17, 19,  0,  4, 21, 11, 18,  1], dtype=int32)

In [21]:
CT = [EAM_rev[CT_array[i]] for i in range(len(CT_array))]
CT

['r', 'y', 'r', 't', 'a', 'e', 'v', 'l', 's', 'b']

In [22]:
''.join(CT)

'ryrtaevlsb'

### Finding the inverse of the key

In [23]:
CT_numbers = [EAM[i] for i in CT]
CT_numbers

[17, 24, 17, 19, 0, 4, 21, 11, 18, 1]

In [24]:
key_matrix

array([[19,  4],
       [18, 19]])

In [25]:
np.linalg.inv(key_matrix)

array([[ 0.06574394, -0.01384083],
       [-0.06228374,  0.06574394]])

In [26]:
np.linalg.det(key_matrix)

289.00000000000006

In [27]:
adj_key_matrix = np.linalg.inv(key_matrix) * round(np.linalg.det(key_matrix)) # important distinction between int and round
adj_key_matrix

array([[ 19.,  -4.],
       [-18.,  19.]])

In [28]:
print(int(5.2), round(5.2))

5 5


In [29]:
print(int(5.7), round(5.7))

5 6


In [30]:
round(np.linalg.det(key_matrix))

289

In [31]:
289 % 26

3

In [32]:
pow(289, -1, 26)

9

In [33]:
key_inverse = (9 * adj_key_matrix) % 26

key_inverse

array([[15., 16.],
       [20., 15.]])

In [34]:
key_inverse

array([[15., 16.],
       [20., 15.]])

### Decryption

In [35]:
CT_array = np.array(CT_numbers)
CT_array

array([17, 24, 17, 19,  0,  4, 21, 11, 18,  1])

In [36]:
CT_blocks = np.split(CT_array, len(CT_numbers)//BL)
CT_blocks

[array([17, 24]),
 array([17, 19]),
 array([0, 4]),
 array([21, 11]),
 array([18,  1])]

In [37]:
PT_blocks = [np.matmul(CT_blocks[i], key_inverse) % 26 for i in range(len(PT)//BL)]
PT_blocks

[array([7., 8.]),
 array([11., 11.]),
 array([2., 8.]),
 array([15.,  7.]),
 array([ 4., 17.])]

In [38]:
PT_array = np.concatenate(PT_blocks)
PT_array

array([ 7.,  8., 11., 11.,  2.,  8., 15.,  7.,  4., 17.])

In [39]:
type(PT_array[0]) # each element is a float, not an integer

numpy.float64

In [40]:
[EAM_rev[round(i)] for i in PT_array] # round(i) is necessary since PT_array[i] is a float

['h', 'i', 'l', 'l', 'c', 'i', 'p', 'h', 'e', 'r']